name: CI

on:
  merge_group:
  pull_request:
  workflow_dispatch:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1

  binary-compatibility-check:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Binary Compatibility Check
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: apiDump
          check-task: apiCheck

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: all tests
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: test
          write-cache-key: main-build-artifacts
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: unit-test-results-${{ matrix.os }}
          path: ./**/build/reports/tests/

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        if: failure()
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Unit test results
        uses: mikepenz/action-junit-report@65fe03598d8d251738592a497a9e8547a5c48eaa # v5
        if: failure()
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - ${{ matrix.os }}

  dependency-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: dependency-guard
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          # Using --no-parallel to avoid the following error during dependency locking:
          # > java.lang.IllegalStateException: Something has been appended to this collector already
          #
          # https://youtrack.jetbrains.com/issue/KT-74241/Dependency-locking-sometimes-fails-with-gradle-kotlin-plugin
          # https://youtrack.jetbrains.com/issue/KT-74394/KGP-isolated-projects-Something-has-been-appended-to-this-collector-already
          fix-task: dependencyGuardBaseline --no-parallel
          check-task: dependencyGuard --no-parallel

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: ktlint
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: ktlintFormat
          check-task: ktlintCheck

  doks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: doks
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: doks
          check-task: doksCheck

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Android Lint in integration-tests
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          build-root-directory: ./integration-tests
          task: lint
          restore-cache-key: main-build-artifacts

      - name: Android Lint in sample
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          build-root-directory: ./sample
          task: lint
          restore-cache-key: main-build-artifacts

      - name: Upload Lint Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ failure() }}
        with:
          name: lint-results
          path: ./**/build/reports/lint-results.html

  kapt-for-dagger-factories:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run integration tests
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          build-root-directory: ./integration-tests
          task: test -Doverride_config-generateDaggerFactoriesWithAnvil=false
          restore-cache-key: main-build-artifacts

      - name: Build the sample
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          build-root-directory: ./sample
          task: assembleDebug -Doverride_config-generateDaggerFactoriesWithAnvil=false

      - name: Upload Test Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ failure() }}
        with:
          # Use the Kotlin version to prevent overrides.
          name: test-results-kapt-${{ matrix.kotlin-version }}
          path: ./**/build/reports/tests/

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        api-level:
          # Consider other devices in case it's needed.
          #- 24
          - 29
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          disable-animations: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          force-avd-creation: false
          profile : Galaxy Nexus
          ram-size : 4096M
          target: default
          script: echo "Generated AVD snapshot for caching."

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          disable-animations: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          force-avd-creation: false
          profile : Galaxy Nexus
          ram-size : 4096M
          target: default
          working-directory: ./sample
          script: ./gradlew connectedCheck --no-build-cache --no-daemon --stacktrace

      - name: Upload results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: instrumentation-test-results
          path: ./**/build/reports/androidTests/connected/**

  integration-tests:
    name: Integration tests
    runs-on: macos-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run integration tests
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          build-root-directory: ./integration-tests
          task: test
          restore-cache-key: main-build-artifacts

      - name: Upload Test Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ failure() }}
        with:
          name: test-results-gradle-integration
          path: ./integration-tests/**/build/reports/tests/

  gradle-tests:
    name: Gradle tests
    runs-on: macos-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Gradle tests
        run: ./gradlew gradleTest --stacktrace

      - name: Upload Test Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ failure() }}
        with:
          name: test-results-gradle-integration
          path: ./**/build/reports/tests/

  build-benchmark-project:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: "Generate Project"
        run: ./gradlew :createBenchmarkProject

      - name: "Build Benchmark Project"
        run: ./gradlew -p benchmark :app:assemble

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - binary-compatibility-check
      - build-benchmark-project
      - dependency-guard
      - doks
      - gradle-tests
      - instrumentation-tests
      - integration-tests
      - kapt-for-dagger-factories
      - ktlint
      - lint
      - unit-tests

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          allowed-skips: publish-snapshot
          jobs: ${{ toJSON(needs) }}
