name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: github.repository == 'square/anvil'
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: gradle/actions/wrapper-validation@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Publish Release 1.9
        run: ./gradlew clean publish --no-build-cache --no-daemon --stacktrace --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ''

      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@cae32133495112d23e3569ad04fef240ba4e7bc8 # v2

      - name: Check if prerelease
        id: prerelease
        run: |
          version=$(grep VERSION_NAME gradle.properties | cut -d'=' -f2)
          if [[ $version == *"-beta"* ]]; then
            echo "isPrerelease=true" >> $GITHUB_OUTPUT
          else
            echo "isPrerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          prerelease: ${{ steps.prerelease.outputs.isPrerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
